fixed passwd compat configure.in again

diff --git a/configure b/configure
--- a/configure
+++ b/configure
@@ -836,7 +836,7 @@ Optional Features:
   --enable-rsync-compat   enable rsync compatibility
   --enable-chrooted-binary
                           install chrooted binary 'scponlyc'
-  --enable-passwd         enable passwd invocation
+  --enable-passwd-compat  enable passwd compatibility
 
 Optional Packages:
   --with-PACKAGE[=ARG]    use PACKAGE [ARG=yes]
@@ -2829,57 +2829,13 @@ else
 
 fi;
 
-# Check whether --enable-passwd or --disable-passwd was given.
-if test "${enable_passwd+set}" = set; then
-  enableval="$enable_passwd"
+# Check whether --enable-passwd-compat or --disable-passwd-compat was given.
+if test "${enable_passwd_compat+set}" = set; then
+  enableval="$enable_passwd_compat"
 
               if test "x$enableval" != "xno"; then
                       cat >>confdefs.h <<\_ACEOF
-#define PASSWD_ENABLE 1
-_ACEOF
-
-                      # Extract the first word of "passwd", so it can be a program name with args.
-set dummy passwd; ac_word=$2
-echo "$as_me:$LINENO: checking for $ac_word" >&5
-echo $ECHO_N "checking for $ac_word... $ECHO_C" >&6
-if test "${ac_cv_path_scponly_PROG_PASSWD+set}" = set; then
-  echo $ECHO_N "(cached) $ECHO_C" >&6
-else
-  case $scponly_PROG_PASSWD in
-  [\\/]* | ?:[\\/]*)
-  ac_cv_path_scponly_PROG_PASSWD="$scponly_PROG_PASSWD" # Let the user override the test with a path.
-  ;;
-  *)
-  as_save_IFS=$IFS; IFS=$PATH_SEPARATOR
-for as_dir in `echo "$PATH:/bin:/usr/bin:/sbin:/usr/sbin" | sed -e 's/:/ /'`
-do
-  IFS=$as_save_IFS
-  test -z "$as_dir" && as_dir=.
-  for ac_exec_ext in '' $ac_executable_extensions; do
-  if $as_executable_p "$as_dir/$ac_word$ac_exec_ext"; then
-    ac_cv_path_scponly_PROG_PASSWD="$as_dir/$ac_word$ac_exec_ext"
-    echo "$as_me:$LINENO: found $as_dir/$ac_word$ac_exec_ext" >&5
-    break 2
-  fi
-done
-done
-
-  ;;
-esac
-fi
-scponly_PROG_PASSWD=$ac_cv_path_scponly_PROG_PASSWD
-
-if test -n "$scponly_PROG_PASSWD"; then
-  echo "$as_me:$LINENO: result: $scponly_PROG_PASSWD" >&5
-echo "${ECHO_T}$scponly_PROG_PASSWD" >&6
-else
-  echo "$as_me:$LINENO: result: no" >&5
-echo "${ECHO_T}no" >&6
-fi
-
-	  test -z $scponly_PROG_PASSWD && echo "Can't find path to 'passwd'" && exit 1
-	  cat >>confdefs.h <<_ACEOF
-#define PROG_PASSWD "$scponly_PROG_PASSWD"
+#define PASSWD_COMPAT 1
 _ACEOF
 
               fi
@@ -3561,7 +3517,7 @@ fi
 
 # unison-compat conditionals:
 if test "x$enable_unison_compat" != "x" && test "x$enable_unison_compat" != "xno"; then
-        { echo "$as_me:$LINENO: enabling unison compatability..." >&5
+	{ echo "$as_me:$LINENO: enabling unison compatability..." >&5
 echo "$as_me: enabling unison compatability..." >&6;}
 	# Extract the first word of "unison", so it can be a program name with args.
 set dummy unison; ac_word=$2
@@ -3611,7 +3567,7 @@ fi
 
 # rsync-compat conditionals:
 if test "x$enable_rsync_compat" != "x" && test "x$enable_rsync_compat" != "xno"; then
-        { echo "$as_me:$LINENO: enabling rsync compatability..." >&5
+	{ echo "$as_me:$LINENO: enabling rsync compatability..." >&5
 echo "$as_me: enabling rsync compatability..." >&6;}
 	# Extract the first word of "rsync", so it can be a program name with args.
 set dummy rsync; ac_word=$2
@@ -3655,6 +3611,55 @@ fi
 	  test -z $scponly_PROG_RSYNC && echo "Can't find path to 'rsync'" && exit 1
 	  cat >>confdefs.h <<_ACEOF
 #define PROG_RSYNC "$scponly_PROG_RSYNC"
+_ACEOF
+
+fi
+
+if test "x$enable_passwd_compat" != "x" && test "x$enable_passwd_compat" != "xno"; then
+	{ echo "$as_me:$LINENO: enabling passwd compatability..." >&5
+echo "$as_me: enabling passwd compatability..." >&6;}
+	# Extract the first word of "passwd", so it can be a program name with args.
+set dummy passwd; ac_word=$2
+echo "$as_me:$LINENO: checking for $ac_word" >&5
+echo $ECHO_N "checking for $ac_word... $ECHO_C" >&6
+if test "${ac_cv_path_scponly_PROG_PASSWD+set}" = set; then
+  echo $ECHO_N "(cached) $ECHO_C" >&6
+else
+  case $scponly_PROG_PASSWD in
+  [\\/]* | ?:[\\/]*)
+  ac_cv_path_scponly_PROG_PASSWD="$scponly_PROG_PASSWD" # Let the user override the test with a path.
+  ;;
+  *)
+  as_save_IFS=$IFS; IFS=$PATH_SEPARATOR
+for as_dir in `echo "$PATH:/bin:/usr/bin:/sbin:/usr/sbin" | sed -e 's/:/ /'`
+do
+  IFS=$as_save_IFS
+  test -z "$as_dir" && as_dir=.
+  for ac_exec_ext in '' $ac_executable_extensions; do
+  if $as_executable_p "$as_dir/$ac_word$ac_exec_ext"; then
+    ac_cv_path_scponly_PROG_PASSWD="$as_dir/$ac_word$ac_exec_ext"
+    echo "$as_me:$LINENO: found $as_dir/$ac_word$ac_exec_ext" >&5
+    break 2
+  fi
+done
+done
+
+  ;;
+esac
+fi
+scponly_PROG_PASSWD=$ac_cv_path_scponly_PROG_PASSWD
+
+if test -n "$scponly_PROG_PASSWD"; then
+  echo "$as_me:$LINENO: result: $scponly_PROG_PASSWD" >&5
+echo "${ECHO_T}$scponly_PROG_PASSWD" >&6
+else
+  echo "$as_me:$LINENO: result: no" >&5
+echo "${ECHO_T}no" >&6
+fi
+
+	  test -z $scponly_PROG_PASSWD && echo "Can't find path to 'passwd'" && exit 1
+	  cat >>confdefs.h <<_ACEOF
+#define PROG_PASSWD "$scponly_PROG_PASSWD"
 _ACEOF
 
 fi
@@ -5467,7 +5472,6 @@ s,@PROG_PW@,$PROG_PW,;t t
 s,@PROG_RM@,$PROG_RM,;t t
 s,@PROG_PWD_MKDB@,$PROG_PWD_MKDB,;t t
 s,@CHROOTED_NAME@,$CHROOTED_NAME,;t t
-s,@scponly_PROG_PASSWD@,$scponly_PROG_PASSWD,;t t
 s,@scponly_PROG_SFTP_SERVER@,$scponly_PROG_SFTP_SERVER,;t t
 s,@scponly_PROG_LS@,$scponly_PROG_LS,;t t
 s,@scponly_PROG_SCP@,$scponly_PROG_SCP,;t t
@@ -5485,6 +5489,7 @@ s,@scponly_PROG_ID@,$scponly_PROG_ID,;t t
 s,@scponly_PROG_ECHO@,$scponly_PROG_ECHO,;t t
 s,@scponly_PROG_UNISON@,$scponly_PROG_UNISON,;t t
 s,@scponly_PROG_RSYNC@,$scponly_PROG_RSYNC,;t t
+s,@scponly_PROG_PASSWD@,$scponly_PROG_PASSWD,;t t
 s,@CPP@,$CPP,;t t
 s,@ALLOCA@,$ALLOCA,;t t
 CEOF
