added "id" program changed version number

diff --git a/configure b/configure
--- a/configure
+++ b/configure
@@ -1207,7 +1207,7 @@ cat >>confdefs.h <<\_ACEOF
 #define PACKAGE_NAME 1
 _ACEOF
 
-PACKAGE_VERSION=3.5
+PACKAGE_VERSION=3.8
 cat >>confdefs.h <<\_ACEOF
 #define PACKAGE_VERSION 1
 _ACEOF
@@ -2948,6 +2948,50 @@ fi
 #define PROG_CHOWN "$scponly_PROG_CHOWN"
 _ACEOF
 
+	# Extract the first word of "chgrp", so it can be a program name with args.
+set dummy chgrp; ac_word=$2
+echo "$as_me:$LINENO: checking for $ac_word" >&5
+echo $ECHO_N "checking for $ac_word... $ECHO_C" >&6
+if test "${ac_cv_path_scponly_PROG_CHGRP+set}" = set; then
+  echo $ECHO_N "(cached) $ECHO_C" >&6
+else
+  case $scponly_PROG_CHGRP in
+  [\\/]* | ?:[\\/]*)
+  ac_cv_path_scponly_PROG_CHGRP="$scponly_PROG_CHGRP" # Let the user override the test with a path.
+  ;;
+  *)
+  as_save_IFS=$IFS; IFS=$PATH_SEPARATOR
+for as_dir in `echo "$PATH:/bin:/usr/bin:/sbin:/usr/sbin" | sed -e 's/:/ /'`
+do
+  IFS=$as_save_IFS
+  test -z "$as_dir" && as_dir=.
+  for ac_exec_ext in '' $ac_executable_extensions; do
+  if $as_executable_p "$as_dir/$ac_word$ac_exec_ext"; then
+    ac_cv_path_scponly_PROG_CHGRP="$as_dir/$ac_word$ac_exec_ext"
+    echo "$as_me:$LINENO: found $as_dir/$ac_word$ac_exec_ext" >&5
+    break 2
+  fi
+done
+done
+
+  ;;
+esac
+fi
+scponly_PROG_CHGRP=$ac_cv_path_scponly_PROG_CHGRP
+
+if test -n "$scponly_PROG_CHGRP"; then
+  echo "$as_me:$LINENO: result: $scponly_PROG_CHGRP" >&5
+echo "${ECHO_T}$scponly_PROG_CHGRP" >&6
+else
+  echo "$as_me:$LINENO: result: no" >&5
+echo "${ECHO_T}no" >&6
+fi
+
+	  test -z $scponly_PROG_CHGRP && echo "Can't find path to 'chgrp'" && exit 1
+	  cat >>confdefs.h <<_ACEOF
+#define PROG_CHGRP "$scponly_PROG_CHGRP"
+_ACEOF
+
 	# Extract the first word of "mkdir", so it can be a program name with args.
 set dummy mkdir; ac_word=$2
 echo "$as_me:$LINENO: checking for $ac_word" >&5
@@ -3127,6 +3171,50 @@ fi
 	  test -z $scponly_PROG_GROUPS && echo "Can't find path to 'groups'" && exit 1
 	  cat >>confdefs.h <<_ACEOF
 #define PROG_GROUPS "$scponly_PROG_GROUPS"
+_ACEOF
+
+	# Extract the first word of "id", so it can be a program name with args.
+set dummy id; ac_word=$2
+echo "$as_me:$LINENO: checking for $ac_word" >&5
+echo $ECHO_N "checking for $ac_word... $ECHO_C" >&6
+if test "${ac_cv_path_scponly_PROG_ID+set}" = set; then
+  echo $ECHO_N "(cached) $ECHO_C" >&6
+else
+  case $scponly_PROG_ID in
+  [\\/]* | ?:[\\/]*)
+  ac_cv_path_scponly_PROG_ID="$scponly_PROG_ID" # Let the user override the test with a path.
+  ;;
+  *)
+  as_save_IFS=$IFS; IFS=$PATH_SEPARATOR
+for as_dir in `echo "$PATH:/bin:/usr/bin:/sbin:/usr/sbin" | sed -e 's/:/ /'`
+do
+  IFS=$as_save_IFS
+  test -z "$as_dir" && as_dir=.
+  for ac_exec_ext in '' $ac_executable_extensions; do
+  if $as_executable_p "$as_dir/$ac_word$ac_exec_ext"; then
+    ac_cv_path_scponly_PROG_ID="$as_dir/$ac_word$ac_exec_ext"
+    echo "$as_me:$LINENO: found $as_dir/$ac_word$ac_exec_ext" >&5
+    break 2
+  fi
+done
+done
+
+  ;;
+esac
+fi
+scponly_PROG_ID=$ac_cv_path_scponly_PROG_ID
+
+if test -n "$scponly_PROG_ID"; then
+  echo "$as_me:$LINENO: result: $scponly_PROG_ID" >&5
+echo "${ECHO_T}$scponly_PROG_ID" >&6
+else
+  echo "$as_me:$LINENO: result: no" >&5
+echo "${ECHO_T}no" >&6
+fi
+
+	  test -z $scponly_PROG_ID && echo "Can't find path to 'id'" && exit 1
+	  cat >>confdefs.h <<_ACEOF
+#define PROG_ID "$scponly_PROG_ID"
 _ACEOF
 
 	# Extract the first word of "echo", so it can be a program name with args.
@@ -5036,10 +5124,12 @@ s,@scponly_PROG_LN@,$scponly_PROG_LN,;t t
 s,@scponly_PROG_MV@,$scponly_PROG_MV,;t t
 s,@scponly_PROG_CHMOD@,$scponly_PROG_CHMOD,;t t
 s,@scponly_PROG_CHOWN@,$scponly_PROG_CHOWN,;t t
+s,@scponly_PROG_CHGRP@,$scponly_PROG_CHGRP,;t t
 s,@scponly_PROG_MKDIR@,$scponly_PROG_MKDIR,;t t
 s,@scponly_PROG_RMDIR@,$scponly_PROG_RMDIR,;t t
 s,@scponly_PROG_PWD@,$scponly_PROG_PWD,;t t
 s,@scponly_PROG_GROUPS@,$scponly_PROG_GROUPS,;t t
+s,@scponly_PROG_ID@,$scponly_PROG_ID,;t t
 s,@scponly_PROG_ECHO@,$scponly_PROG_ECHO,;t t
 s,@scponly_PROG_RSYNC@,$scponly_PROG_RSYNC,;t t
 s,@CPP@,$CPP,;t t
